#!/usr/bin/env python3
"""Win/loss verification to 10^6 for selected cells of the extended sweep.

Cells covered: the diagonal (m, a=m) for m = 2..12, plus (2,8), (3,9), (4,8),
(2,4), (2,6), (3,6), (4,12), (6,12). Every game in those cells that carries a
law from extended_sweep.py is verified -- all r, both branch orders. This is a
census of those cells, not a sample.

Method is imported from harsh_verify.py rather than re-implemented: win/loss
bits only, move sets from compile_rule, early exit on the first winning move,
no Grundy values.

Reads extended_raw.json; modifies nothing. Writes DIAGONAL_VERIFY.md and
diagonal_verify_raw.json. No OEIS calls.

Firewall: results only -- holds-to-10^6 or the first counterexample. No pattern
claims, no reworded conjectures.
"""

import json
import time

from harsh_verify import win_loss_flags, first_counterexample, N_HARSH

SRC = "extended_raw.json"
OUT_MD = "DIAGONAL_VERIFY.md"
OUT_RAW = "diagonal_verify_raw.json"

DIAGONAL = [(m, m) for m in range(2, 13)]
EXTRA = [(2, 8), (3, 9), (4, 8), (2, 4), (2, 6), (3, 6), (4, 12), (6, 12)]
CELLS = DIAGONAL + EXTRA


def main():
    t0 = time.time()
    src = json.load(open(SRC))
    cellset = set(CELLS)
    games = [z for z in src["records"] if z["law"] and (z["m"], z["a"]) in cellset]
    games.sort(key=lambda z: (z["m"], z["a"], z["branch_order"], z["r"]))
    print(f"cells: {len(CELLS)}   games with a law: {len(games)}")

    results = []
    for i, z in enumerate(games, 1):
        law = z["law"]
        t = time.time()
        isP = win_loss_flags(z["rule"], N_HARSH)
        ce = first_counterexample(isP, law["modulus"], law["residues"], law["from"])
        secs = time.time() - t
        rec = {
            "m": z["m"], "a": z["a"], "r": z["r"],
            "branch_order": z["branch_order"],
            "rule": z["rule"], "dsl": z["dsl"], "pretty": z["pretty"],
            "law": law, "conjecture": z["conjecture"],
            "N_harsh": N_HARSH,
            "first_counterexample": ce,
            "holds": ce is None,
            "seconds": round(secs, 1),
        }
        if ce is not None:
            rec["counterexample_detail"] = {
                "n": ce,
                "computed": "P" if isP[ce] else "N",
                "law_predicts": "P" if ce % law["modulus"] in set(law["residues"]) else "N",
            }
        results.append(rec)
        print(f"  {i:>3}/{len(games)}  "
              f"{'HOLDS' if ce is None else 'COUNTEREXAMPLE n=%d' % ce}"
              f"  ({secs:.0f}s)  m={z['m']} a={z['a']} r={z['r']} {z['branch_order']}")

    held = [x for x in results if x["holds"]]
    broke = [x for x in results if not x["holds"]]
    total = time.time() - t0

    by_cell = {}
    for x in results:
        by_cell.setdefault((x["m"], x["a"]), []).append(x)

    L = []
    w = L.append
    w("# Diagonal and selected-cell verification to 10^6")
    w("")
    w("Generated by `diagonal_verify.py`. Results only; nothing here is proved.")
    w("All laws below are unproven conjectures pending human verification.")
    w("")
    w("## Scope")
    w("")
    w(f"- Diagonal cells (m, a = m), m = 2..12: {len(DIAGONAL)} cells")
    w("- Additional cells: " + ", ".join(f"({m},{a})" for m, a in EXTRA))
    w(f"- Every game carrying a law in those cells — all r, both branch orders:")
    w(f"  **{len(games)}** games. A census of these cells, not a sample.")
    w("")
    w("## Method")
    w("")
    w("`win_loss_flags` and `first_counterexample` are imported from")
    w("`harsh_verify.py`, not re-implemented. Win/loss bits only, move sets from")
    w("`compile_rule`, early exit on the first winning move, no Grundy values,")
    w(f"tested to N = {N_HARSH:,}. No OEIS calls.")
    w("")
    w("## Result")
    w("")
    w(f"- Laws holding to 10^6: **{len(held)} / {len(games)}**")
    w(f"- Laws with a counterexample below 10^6: **{len(broke)} / {len(games)}**")
    w("")
    w("### By cell")
    w("")
    w("| cell (m, a) | games | hold | counterexample |")
    w("|---|---:|---:|---:|")
    for m, a in CELLS:
        recs = by_cell.get((m, a), [])
        h = sum(1 for x in recs if x["holds"])
        b = len(recs) - h
        tag = " *(diagonal)*" if m == a else ""
        w(f"| ({m}, {a}){tag} | {len(recs)} | {h} | {b} |")
    w("")
    w("### Per game")
    w("")
    w("| m | a | r | branch order | modulus | residues | preperiod | result |")
    w("|---:|---:|---:|---|---:|---|---:|---|")
    for x in results:
        law = x["law"]
        res = ", ".join(map(str, law["residues"]))
        if x["holds"]:
            verdict = "holds to 10^6"
        else:
            d = x["counterexample_detail"]
            verdict = (f"**first counterexample n = {d['n']}** "
                       f"(computed {d['computed']}, law predicts {d['law_predicts']})")
        w(f"| {x['m']} | {x['a']} | {x['r']} | {x['branch_order']} | "
          f"{law['modulus']} | {res} | {law['from']} | {verdict} |")
    w("")
    if broke:
        w("### Counterexamples in full")
        w("")
        for x in broke:
            d = x["counterexample_detail"]
            w(f"#### `{x['dsl']}`")
            w("")
            w(f"- Rule: subtract s ∈ {x['pretty']}")
            w("")
            w("Law as emitted by the sweep, reproduced verbatim:")
            w("")
            w("```")
            w(x["conjecture"])
            w("```")
            w("")
            w(f"**first counterexample: n = {d['n']}** — win/loss computation says "
              f"{d['computed']}, the law predicts {d['law_predicts']}.")
            w("")

    with open(OUT_MD, "w") as fh:
        fh.write("\n".join(L).rstrip() + "\n")
    with open(OUT_RAW, "w") as fh:
        json.dump({
            "source": SRC, "cells": CELLS, "n_harsh": N_HARSH,
            "games": len(games), "held": len(held), "broke": len(broke),
            "total_seconds": round(total, 1),
            "results": results,
        }, fh, indent=1)

    print(f"\nholds to 10^6 : {len(held)}/{len(games)}")
    print(f"counterexample: {len(broke)}/{len(games)}")
    for x in broke:
        print(f"   {x['dsl']}  first n={x['first_counterexample']}")
    print(f"total time    : {total:.1f}s")
    print(f"wrote {OUT_MD}, {OUT_RAW}")


if __name__ == "__main__":
    main()
