#!/usr/bin/env python3
"""Diagonal workbook generator.

Emits DIAGONAL_WORKBOOK.md for the diagonal games

    ["ifmod", m, r, ["squares"], ["const",[m]]]

at (m, r) = (3,1), (5,2), (7,3), (9,4), plus the two cells with no detected
law, (2,1) and (4,1).

Imports game_hunter read-only; modifies nothing. Reads extended_raw.json for
recorded laws. Writes DIAGONAL_WORKBOOK.md and diagonal_workbook_raw.json.
No OEIS calls.

Workbook firewall: this script emits DATA and verbatim law lines only. It emits
no closure argument, no induction sketch, no account of chain behaviour, no
squares-mod table, and no commentary on the switching class r. All reasoning
belongs to the human.
"""

import json
import time
from math import isqrt

import game_hunter as gh

SRC = "extended_raw.json"
OUT_MD = "DIAGONAL_WORKBOOK.md"
OUT_RAW = "diagonal_workbook_raw.json"

GAMES = [(3, 1), (5, 2), (7, 3), (9, 4), (2, 1), (4, 1)]

N_ENGINE = 20_000        # engine Grundy range, also the agreement range
N_STANDALONE = 200_000   # independent win/loss range
NO_LAW_LINE = "no law detected up to modulus 200"


def rule_for(m, r):
    return ["ifmod", m, r, ["squares"], ["const", [m]]]


# ---------------------------------------------------------------------------
# fresh standalone move rule -- deliberately does NOT use gh.compile_rule
# ---------------------------------------------------------------------------

def make_standalone_moves(m, r):
    """Legal subtraction amounts at n, written from scratch for this game.

    n = r (mod m): the perfect squares k^2 with k^2 <= n.
    otherwise    : the single amount m, when m <= n.
    """
    def moves(n):
        if n % m == r:
            return [k * k for k in range(1, isqrt(n) + 1)]
        return [m] if m <= n else []
    return moves


def standalone_p_flags(m, r, N):
    """isP[n] == 1 iff n is a P-position, by independent win/loss recursion."""
    isP = bytearray(N + 1)
    isP[0] = 1
    for n in range(1, N + 1):
        found = 0
        if n % m == r:
            k = 1
            while k * k <= n:
                if isP[n - k * k]:
                    found = 1
                    break
                k += 1
        else:
            if m <= n and isP[n - m]:
                found = 1
        if not found:
            isP[n] = 1
    return isP


def law_holds(isP, law, upto):
    res = set(law["residues"])
    mod = law["modulus"]
    for n in range(law["from"], upto + 1):
        if bool(isP[n]) != (n % mod in res):
            return False, n
    return True, None


def main():
    t0 = time.time()
    src = json.load(open(SRC))
    recorded = {(z["m"], z["r"]): z for z in src["records"]
                if z["branch_order"] == "squares / F" and z["a"] == z["m"]}

    L = []
    w = L.append
    w("# Diagonal workbook")
    w("")
    w("Generated by `diagonal_workbook.py`. Data and verbatim law lines only.")
    w("Nothing here is proved; every law below is an unproven conjecture pending")
    w("human verification.")
    w("")
    w("Games covered: `[\"ifmod\", m, r, [\"squares\"], [\"const\",[m]]]` at")
    w("(m, r) = " + ", ".join(f"({m},{r})" for m, r in GAMES) + ".")
    w("")
    w("Column legend for the position tables:")
    w("")
    w("- **mode** — `squares` when n ≡ r (mod m), otherwise `fallback`")
    w("- **legal moves** — in `squares` mode, the count of legal squares followed")
    w("  by the three smallest; in `fallback` mode, the move set itself")
    w("- **fallback target** — in `fallback` mode, the position reached, with its")
    w("  residue mod m and mod 2m; a dash in `squares` mode")
    w("- **P/N** — from the engine's Grundy values (`G(n) == 0` is P)")
    w("")

    raw = []
    for m, r in GAMES:
        rule = rule_for(m, r)
        rec = recorded.get((m, r))
        law = rec["law"] if rec else None
        conj = rec["conjecture"] if rec else None

        G = gh.grundy_sequence(rule, N_ENGINE)
        engine_isP = [1 if g == 0 else 0 for g in G]
        f_engine = gh.compile_rule(rule)

        # ---- (d) standalone ----
        t_sa = time.time()
        isP = standalone_p_flags(m, r, N_STANDALONE)
        sa_secs = time.time() - t_sa
        disagree = [n for n in range(N_ENGINE + 1) if isP[n] != engine_isP[n]]
        if law:
            holds_200k, first_bad = law_holds(isP, law, N_STANDALONE)
        else:
            holds_200k, first_bad = None, None

        w("---")
        w("")
        w(f"## m = {m}, r = {r}")
        w("")
        w("### a. Rule and law")
        w("")
        w(f"- **DSL**: `{json.dumps(rule)}`")
        w(f"- **Human-readable**: subtract s ∈ {gh.pretty(rule)}")
        w("")
        if law:
            w("Law as recorded in `extended_raw.json`, reproduced verbatim:")
            w("")
            w("```")
            w(conj)
            w("```")
        else:
            w("```")
            w(NO_LAW_LINE)
            w("```")
        w("")

        # ---- (b) position table ----
        w(f"### b. Positions n = 0..{6 * m}")
        w("")
        w("| n | n mod m | n mod 2m | mode | legal moves | fallback target | P/N |")
        w("|---:|---:|---:|---|---|---|:---:|")
        rows = []
        for n in range(0, 6 * m + 1):
            mv = sorted(f_engine(n))
            in_squares = (n % m == r)
            if in_squares:
                three = ", ".join(map(str, mv[:3])) if mv else "none"
                mv_s = f"{len(mv)} squares: {three}" if mv else "0 squares: none"
                fb = "–"
            else:
                mv_s = "{" + ", ".join(map(str, mv)) + "}" if mv else "{} (none)"
                if mv:
                    tgt = n - m
                    fb = f"{tgt} (≡{tgt % m} mod {m}, ≡{tgt % (2 * m)} mod {2 * m})"
                else:
                    fb = "–"
            pn = "P" if engine_isP[n] else "N"
            w(f"| {n} | {n % m} | {n % (2 * m)} | {'squares' if in_squares else 'fallback'} "
              f"| {mv_s} | {fb} | {pn} |")
            rows.append({"n": n, "mod_m": n % m, "mod_2m": n % (2 * m),
                         "mode": "squares" if in_squares else "fallback",
                         "moves": mv, "pn": pn})
        w("")

        # ---- (c) chain view ----
        w(f"### c. Chains, classes c ≠ {r} (mod {m})")
        w("")
        w(f"Each line lists n : status for n = c, c+{m}, c+2·{m}, … up to {6 * m},")
        w("smallest n first.")
        w("")
        w("```")
        chains = {}
        for c in range(m):
            if c == r:
                continue
            seq = [(n, "P" if engine_isP[n] else "N")
                   for n in range(c, 6 * m + 1, m)]
            chains[c] = seq
            w(f"c = {c} : " + "  ".join(f"{n}:{s}" for n, s in seq))
        w("```")
        w("")

        # ---- (d) cross-implementation check ----
        w("### d. Cross-implementation check")
        w("")
        w("`make_standalone_moves` / `standalone_p_flags` in")
        w("`diagonal_workbook.py` re-implement this game's move rule and win/loss")
        w("recursion from scratch. They do not call `compile_rule`,")
        w("`grundy_sequence`, or any detector.")
        w("")
        w(f"- Independent range: n = 0 .. {N_STANDALONE:,} ({sa_secs:.1f}s)")
        if disagree:
            w(f"- Agreement with the engine over n ≤ {N_ENGINE:,}: "
              f"**{len(disagree)} disagreement(s)**, first at n = {disagree[0]}")
        else:
            w(f"- Agreement with the engine over n ≤ {N_ENGINE:,}: "
              f"**agrees at every n**, 0 disagreements")
        if law:
            if holds_200k:
                w(f"- Recorded law to {N_STANDALONE:,}: **holds**, no counterexample")
            else:
                w(f"- Recorded law to {N_STANDALONE:,}: "
                  f"**first counterexample n = {first_bad}** "
                  f"(computed {'P' if isP[first_bad] else 'N'}, law predicts "
                  f"{'P' if first_bad % law['modulus'] in set(law['residues']) else 'N'})")
        else:
            w(f"- Recorded law to {N_STANDALONE:,}: not applicable — {NO_LAW_LINE}")
        w("")

        raw.append({
            "m": m, "r": r, "rule": rule, "dsl": json.dumps(rule),
            "pretty": gh.pretty(rule),
            "law": law, "conjecture": conj if law else NO_LAW_LINE,
            "table": rows,
            "chains": {str(c): chains[c] for c in chains},
            "n_engine": N_ENGINE, "n_standalone": N_STANDALONE,
            "disagreements": len(disagree),
            "first_disagreement": disagree[0] if disagree else None,
            "law_holds_to_200000": holds_200k,
            "first_counterexample": first_bad,
            "standalone_seconds": round(sa_secs, 1),
        })
        print(f"  m={m} r={r}  law={'yes' if law else 'none'}  "
              f"disagreements={len(disagree)}  holds200k={holds_200k}  ({sa_secs:.1f}s)")

    w("---")
    w("")
    w("All laws above are unproven conjectures pending human verification.")

    with open(OUT_MD, "w") as fh:
        fh.write("\n".join(L) + "\n")
    with open(OUT_RAW, "w") as fh:
        json.dump({"source": SRC, "games": GAMES,
                   "n_engine": N_ENGINE, "n_standalone": N_STANDALONE,
                   "records": raw}, fh, indent=1)

    print(f"\nwrote {OUT_MD}, {OUT_RAW}   total {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
