#!/usr/bin/env python3
"""Mode-switching family sweep.

Sweeps  ["ifmod", m, r, ["squares"], F]  and  ["ifmod", m, r, F, ["squares"]]
for m in 2..8, every r in 0..m-1, and F drawn from a fixed catalogue.

Each game gets the standard analysis at N=3000. Any game whose detector reports
a residue law is re-analysed at N=20000 to see whether the same conjecture line
reappears.

Imports game_hunter read-only; modifies nothing in it. Writes FAMILY_CENSUS.md
and family_census_raw.json.

NO OEIS: this module never calls gh.oeis_lookup, never calls gh.analyze_rule
(whose deep path performs lookups), and opens no network connection. It uses
gh.grundy_sequence / gh.detect_all / gh.score_game / gh.draft_conjectures only.

Census firewall: descriptive counts only (games run, laws found, modulus
frequency). This script does not propose any relationship between (m, r, F) and
the emergent modulus, and it never rewords a conjecture -- verbatim conjecture
lines are carried through to family_census_raw.json untouched.
"""

import hashlib
import json
import time

import game_hunter as gh

N_SCAN = 3000
N_DEEP = 20000
MS = (2, 3, 4, 5, 6, 7, 8)

F_CATALOGUE = (
    [["const", [a]] for a in range(1, 10)]
    + [["range", 1, k] for k in (2, 3, 4)]
    + [["const", [3, 8, 9]], ["const", [1, 6, 9]], ["range", 2, 2], ["range", 3, 6]]
)

SQUARES = ["squares"]


def residue_conjecture(det, stats):
    """The verbatim residue CONJECTURE line, or None. Never reworded."""
    for line in gh.draft_conjectures(det, stats):
        if line.startswith("CONJECTURE: for n ≥") and "(mod" in line \
                and "P-positions are exactly" in line:
            return line
    return None


def build_games():
    games = []
    for m in MS:
        for r in range(m):
            for F in F_CATALOGUE:
                games.append((m, r, "squares / F", F, ["ifmod", m, r, SQUARES, F]))
                games.append((m, r, "F / squares", F, ["ifmod", m, r, F, SQUARES]))
    return games


def main():
    t0 = time.time()
    games = build_games()
    print(f"games to sweep: {len(games)}")

    records = []
    t_scan = time.time()
    n_deep_runs = 0
    for i, (m, r, order, F, rule) in enumerate(games, 1):
        rec = {
            "m": m, "r": r, "branch_order": order,
            "F": F, "F_pretty": gh.pretty(F),
            "rule": rule, "pretty": gh.pretty(rule),
            "rule_size": gh.rule_size(rule),
            "valid": gh.valid(rule),
            "N_scan": N_SCAN,
        }

        G = gh.grundy_sequence(rule, N_SCAN)
        det, stats = gh.detect_all(rule, G)
        score, tier, notes = gh.score_game(det, stats, gh.rule_size(rule))
        # same fingerprint convention analyze_rule uses, so census rows can be
        # cross-referenced against SHORTLIST.md entries by hash
        ghash = hashlib.sha1(str(G[1:min(N_SCAN, 300)]).encode()).hexdigest()[:12]
        rec.update({"tier": tier, "score": score, "notes": notes,
                    "game_hash": ghash})

        law = det["residue"]
        rec["law"] = law
        rec["conjecture_scan"] = residue_conjecture(det, stats)

        if law:
            n_deep_runs += 1
            G2 = gh.grundy_sequence(rule, N_DEEP)
            det2, stats2 = gh.detect_all(rule, G2)
            law2 = det2["residue"]
            conj2 = residue_conjecture(det2, stats2)
            rec["law_deep"] = law2
            rec["conjecture_deep"] = conj2
            rec["N_deep"] = N_DEEP
            rec["survived_20000"] = bool(conj2) and conj2 == rec["conjecture_scan"]
        else:
            rec["law_deep"] = None
            rec["conjecture_deep"] = None
            rec["N_deep"] = None
            rec["survived_20000"] = None

        records.append(rec)
        if i % 200 == 0:
            print(f"  {i}/{len(games)}  ({time.time() - t_scan:.0f}s elapsed)")

    sweep_secs = time.time() - t_scan

    # ---- sort: by law modulus, then m; games with no law last ----
    BIG = 10 ** 9

    def sort_key(x):
        mod = x["law"]["modulus"] if x["law"] else BIG
        return (mod, x["m"], x["r"], x["branch_order"], json.dumps(x["F"]))

    records.sort(key=sort_key)

    # ---- descriptive counts only ----
    with_law = [x for x in records if x["law"]]
    survived = [x for x in with_law if x["survived_20000"]]
    tier_counts = {}
    for x in records:
        tier_counts[x["tier"]] = tier_counts.get(x["tier"], 0) + 1
    mod_counts = {}
    for x in with_law:
        k = x["law"]["modulus"]
        mod_counts[k] = mod_counts.get(k, 0) + 1

    L = []
    w = L.append
    w("# Mode-switching family census")
    w("")
    w("Generated by `family_sweep.py`. Every entry below is detector output at a")
    w("finite range. Nothing here is proved.")
    w("")
    w("## Sweep definition")
    w("")
    w("- Rules: `[\"ifmod\", m, r, [\"squares\"], F]` and `[\"ifmod\", m, r, F, [\"squares\"]]`")
    w("- `m` in {2,3,4,5,6,7,8}, `r` in 0..m-1")
    w("- `F` catalogue (16 entries): `[\"const\",[a]]` for a = 1..9; `[\"range\",1,k]`")
    w("  for k = 2,3,4; plus `[\"const\",[3,8,9]]`, `[\"const\",[1,6,9]]`,")
    w("  `[\"range\",2,2]`, `[\"range\",3,6]`")
    w(f"- Scan range N = {N_SCAN}; any detected residue law re-analysed at N = {N_DEEP}")
    w("- **No OEIS calls anywhere in this sweep.**")
    w("")
    w("`branch_order` reads *then-branch / else-branch*: `squares / F` means the")
    w("squares move set applies when n ≡ r (mod m) and `F` applies otherwise.")
    w("")
    w("\"Survived at 20000\" means the residue CONJECTURE line emitted at N=20000 is")
    w("character-identical to the one emitted at N=3000. The verbatim conjecture")
    w("lines are carried through to `family_census_raw.json`; the columns below are")
    w("the detector's own structured fields.")
    w("")
    w("## Counts")
    w("")
    w(f"- Games swept: **{len(records)}** (all passed `valid()`)")
    w(f"- Games with a detected residue law at N={N_SCAN}: **{len(with_law)}**")
    w(f"- Of those, same conjecture line at N={N_DEEP}: **{len(survived)}**")
    w(f"- Re-analyses run at N={N_DEEP}: {n_deep_runs}")
    w("")
    w("Tier distribution at N=%d:" % N_SCAN)
    w("")
    w("| tier | games |")
    w("|---|---:|")
    for k in sorted(tier_counts, key=lambda k: -tier_counts[k]):
        w(f"| {k} | {tier_counts[k]} |")
    w("")
    w("Law modulus frequency:")
    w("")
    w("| modulus | games |")
    w("|---:|---:|")
    for k in sorted(mod_counts):
        w(f"| {k} | {mod_counts[k]} |")
    w("")
    w("## Census")
    w("")
    w("Sorted by law modulus, then m. Games with no detected residue law carry")
    w("`-` in the law columns and sort last.")
    w("")
    w("| m | r | branch order | F | tier | modulus | residues | preperiod | survived @20000 |")
    w("|---:|---:|---|---|---|---:|---|---:|:---:|")
    for x in records:
        law = x["law"]
        if law:
            mod = str(law["modulus"])
            res = ", ".join(map(str, law["residues"]))
            pre = str(law["from"])
            sur = "yes" if x["survived_20000"] else "no"
        else:
            mod = res = pre = sur = "-"
        w(f"| {x['m']} | {x['r']} | {x['branch_order']} | `{x['F_pretty']}` | "
          f"{x['tier']} | {mod} | {res} | {pre} | {sur} |")
    w("")
    w("---")
    w("")
    w("All laws above are unproven conjectures pending human verification.")

    with open("FAMILY_CENSUS.md", "w") as fh:
        fh.write("\n".join(L) + "\n")
    with open("family_census_raw.json", "w") as fh:
        json.dump({
            "n_scan": N_SCAN, "n_deep": N_DEEP,
            "games": len(records), "with_law": len(with_law),
            "survived": len(survived),
            "sweep_seconds": round(sweep_secs, 1),
            "records": records,
        }, fh, indent=1)

    print(f"\ngames swept      : {len(records)}")
    print(f"residue laws     : {len(with_law)}")
    print(f"survived @20000  : {len(survived)}")
    print(f"tiers            : {tier_counts}")
    print(f"modulus freq     : {dict(sorted(mod_counts.items()))}")
    print(f"sweep time       : {sweep_secs:.1f}s   total {time.time() - t0:.1f}s")
    print("wrote FAMILY_CENSUS.md, family_census_raw.json")


if __name__ == "__main__":
    main()
