#!/usr/bin/env python3
"""Gap closure for the harsh survival test.

The seed=13 sample in harsh_verify.py drew 20/20 from the `squares / F` branch
order, leaving every `F / squares` law untested at 10^6. This script applies the
same method to ALL of them -- not a sample.

The method is imported from harsh_verify rather than re-implemented, so the two
runs are guaranteed to use identical code: win/loss bits only, move sets from
compile_rule, early exit on the first winning move, no Grundy values.

Imports game_hunter and harsh_verify read-only; modifies neither. Appends a
section to HARSH_VERIFY.md and adds records to harsh_verify_raw.json under a
separate key (the seed=13 sample's records are left untouched). No OEIS calls.

Firewall: results only. No pattern claims, no reworded conjectures.
"""

import json
import time

from harsh_verify import win_loss_flags, first_counterexample, N_HARSH

SRC = "family_census_raw.json"
MD = "HARSH_VERIFY.md"
RAW = "harsh_verify_raw.json"
ORDER = "F / squares"


def main():
    t0 = time.time()
    src = json.load(open(SRC))
    games = [r for r in src["records"] if r["law"] and r["branch_order"] == ORDER]
    games.sort(key=lambda x: (x["law"]["modulus"], x["m"], x["r"], x["F_pretty"]))
    print(f"{ORDER} laws to test: {len(games)}")

    results = []
    for i, g in enumerate(games, 1):
        rule = g["rule"]
        law = g["law_deep"] or g["law"]
        t = time.time()
        isP = win_loss_flags(rule, N_HARSH)
        ce = first_counterexample(isP, law["modulus"], law["residues"], law["from"])
        secs = time.time() - t
        rec = {
            "rule": rule, "dsl": json.dumps(rule), "pretty": g["pretty"],
            "m": g["m"], "r": g["r"], "branch_order": g["branch_order"],
            "F_pretty": g["F_pretty"], "game_hash": g["game_hash"],
            "law": law,
            "conjecture_census": g["conjecture_deep"] or g["conjecture_scan"],
            "N_harsh": N_HARSH,
            "first_counterexample": ce,
            "holds": ce is None,
            "seconds": round(secs, 1),
        }
        if ce is not None:
            rec["counterexample_detail"] = {
                "n": ce,
                "computed": "P" if isP[ce] else "N",
                "law_predicts": "P" if ce % law["modulus"] in set(law["residues"]) else "N",
            }
        results.append(rec)
        print(f"  {i:>2}/{len(games)}  "
              f"{'HOLDS' if ce is None else 'COUNTEREXAMPLE n=%d' % ce}"
              f"  ({secs:.0f}s)  {g['pretty'][:46]}")

    held = [r for r in results if r["holds"]]
    broke = [r for r in results if not r["holds"]]
    total = time.time() - t0

    # ---- append section to HARSH_VERIFY.md ----
    L = []
    w = L.append
    w("")
    w("---")
    w("")
    w(f"# Gap closure: every `{ORDER}` law")
    w("")
    w("Generated by `harsh_verify_gap.py`. Results only; nothing here is proved.")
    w("")
    w("## Why this section exists")
    w("")
    w(f"The seed=13 sample above drew 20 of 20 games from the `squares / F` branch")
    w(f"order, so no `{ORDER}` law was tested at 10^6. This section covers **all**")
    w(f"**{len(games)}** of them — a census of that branch order, not a sample.")
    w("")
    w("## Method")
    w("")
    w("Identical to the section above: `win_loss_flags` and `first_counterexample`")
    w("are imported from `harsh_verify.py`, not re-implemented. Win/loss bits only,")
    w("move sets from `compile_rule`, early exit on the first winning move, no")
    w(f"Grundy values, tested to N = {N_HARSH:,}. No OEIS calls.")
    w("")
    w("## Result")
    w("")
    w(f"- Laws holding to 10^6: **{len(held)} / {len(games)}**")
    w(f"- Laws with a counterexample below 10^6: **{len(broke)} / {len(games)}**")
    w("")
    w("| DSL | m | r | F | modulus | residues | preperiod | result |")
    w("|---|---:|---:|---|---:|---|---:|---|")
    for r in results:
        law = r["law"]
        res = ", ".join(map(str, law["residues"]))
        if r["holds"]:
            verdict = "holds to 10^6"
        else:
            d = r["counterexample_detail"]
            verdict = (f"**first counterexample n = {d['n']}** "
                       f"(computed {d['computed']}, law predicts {d['law_predicts']})")
        w(f"| `{r['dsl']}` | {r['m']} | {r['r']} | `{r['F_pretty']}` | "
          f"{law['modulus']} | {res} | {law['from']} | {verdict} |")
    w("")
    w("## Per game")
    w("")
    for r in results:
        w(f"### `{r['dsl']}`")
        w("")
        w(f"- Rule: subtract s ∈ {r['pretty']}")
        w(f"- game_hash: `{r['game_hash']}`")
        w(f"- Tested to N = {r['N_harsh']:,} in {r['seconds']}s")
        w("")
        w("Census conjecture line, reproduced verbatim:")
        w("")
        w("```")
        w(r["conjecture_census"])
        w("```")
        w("")
        if r["holds"]:
            w("**holds to 10^6** — no counterexample found.")
        else:
            d = r["counterexample_detail"]
            w(f"**first counterexample: n = {d['n']}** — win/loss computation says "
              f"{d['computed']}, the law predicts {d['law_predicts']}.")
        w("")
    w("---")
    w("")
    w("All laws above are unproven conjectures pending human verification.")

    with open(MD, "a") as fh:
        fh.write("\n".join(L) + "\n")

    # ---- add records to harsh_verify_raw.json under a separate key ----
    raw = json.load(open(RAW))
    raw["gap_f_squares"] = {
        "note": "all F / squares laws, not a sample; method imported from harsh_verify.py",
        "branch_order": ORDER,
        "games": len(games),
        "held": len(held),
        "broke": len(broke),
        "n_harsh": N_HARSH,
        "seconds": round(total, 1),
        "results": results,
    }
    with open(RAW, "w") as fh:
        json.dump(raw, fh, indent=1)

    print(f"\nholds to 10^6 : {len(held)}/{len(games)}")
    print(f"counterexample: {len(broke)}/{len(games)}")
    for r in broke:
        print(f"   {r['dsl']}  first n={r['first_counterexample']}")
    print(f"total time    : {total:.1f}s")
    print(f"appended section to {MD}; added gap_f_squares to {RAW}")


if __name__ == "__main__":
    main()
