#!/usr/bin/env python3
"""Harsh survival test for a seeded sample of census laws.

Takes a seed=13 sample of 20 games from the 389 census games that carry a
residue law, and tests each law to N = 1,000,000 by a win/loss-only recursion.

Deliberately NOT a Grundy computation: only a P/N bit per position is kept, and
the scan over a position's move set early-exits on the first move that reaches
a P-position. Move sets come from gh.compile_rule.

Imports game_hunter read-only; modifies nothing in it. Writes HARSH_VERIFY.md
and harsh_verify_raw.json. No OEIS calls.

Firewall: results only -- holds-to-10^6 or the first counterexample. No pattern
claims, no reworded conjectures.
"""

import json
import random
import time

import game_hunter as gh

SRC = "family_census_raw.json"
SEED = 13
SAMPLE_N = 20
N_HARSH = 1_000_000


def win_loss_flags(rule, N):
    """isP[n] == 1 iff n is a P-position. Win/loss only; no Grundy values."""
    f = gh.compile_rule(rule)
    isP = bytearray(N + 1)
    isP[0] = 1                       # no moves: previous player wins
    for n in range(1, N + 1):
        found = 0
        for s in f(n):               # early-exit on the first winning move
            if isP[n - s]:
                found = 1
                break
        if not found:
            isP[n] = 1
    return isP


def first_counterexample(isP, modulus, residues, start):
    res = set(residues)
    for n in range(start, len(isP)):
        if bool(isP[n]) != (n % modulus in res):
            return n
    return None


def main():
    t0 = time.time()
    src = json.load(open(SRC))

    pool = [r for r in src["records"] if r["law"]]
    pool.sort(key=lambda x: (x["law"]["modulus"], x["m"], x["r"],
                             x["branch_order"], x["F_pretty"]))
    sample = random.Random(SEED).sample(pool, SAMPLE_N)
    print(f"pool with laws: {len(pool)}; sampling {SAMPLE_N} with seed={SEED}")

    results = []
    for i, g in enumerate(sample, 1):
        rule = g["rule"]
        law = g["law_deep"] or g["law"]
        t = time.time()
        isP = win_loss_flags(rule, N_HARSH)
        ce = first_counterexample(isP, law["modulus"], law["residues"], law["from"])
        secs = time.time() - t
        rec = {
            "rule": rule, "dsl": json.dumps(rule), "pretty": g["pretty"],
            "m": g["m"], "r": g["r"], "branch_order": g["branch_order"],
            "F_pretty": g["F_pretty"], "game_hash": g["game_hash"],
            "law": law,
            "conjecture_census": g["conjecture_deep"] or g["conjecture_scan"],
            "N_harsh": N_HARSH,
            "first_counterexample": ce,
            "holds": ce is None,
            "seconds": round(secs, 1),
        }
        if ce is not None:
            rec["counterexample_detail"] = {
                "n": ce,
                "computed": "P" if isP[ce] else "N",
                "law_predicts": "P" if ce % law["modulus"] in set(law["residues"]) else "N",
            }
        results.append(rec)
        print(f"  {i:>2}/{SAMPLE_N}  {'HOLDS' if ce is None else 'COUNTEREXAMPLE n=%d' % ce}"
              f"  ({secs:.0f}s)  {g['pretty'][:44]}")

    held = [r for r in results if r["holds"]]
    broke = [r for r in results if not r["holds"]]

    L = []
    w = L.append
    w("# Harsh survival test")
    w("")
    w("Generated by `harsh_verify.py`. Results only; nothing here is proved.")
    w("")
    w("## Method")
    w("")
    w(f"- Pool: the **{len(pool)}** census games carrying a residue law")
    w(f"- Sample: **{SAMPLE_N}** games, `random.Random({SEED}).sample(...)` over the")
    w("  pool sorted by (modulus, m, r, branch order, F)")
    w(f"- Each law tested to N = {N_HARSH:,}")
    w("- Win/loss only: one P/N bit per position, **no Grundy values computed**")
    w("- Move sets from `compile_rule`; the scan over a position's moves")
    w("  early-exits on the first move reaching a P-position")
    w("- No OEIS calls")
    w("")
    w("Sample composition: the pool is "
      f"{sum(1 for x in pool if x['branch_order'] == 'squares / F')} `squares / F` "
      f"and {sum(1 for x in pool if x['branch_order'] == 'F / squares')} `F / squares`; "
      "this sample drew "
      f"{sum(1 for x in sample if x['branch_order'] == 'squares / F')} and "
      f"{sum(1 for x in sample if x['branch_order'] == 'F / squares')} respectively.")
    w("")
    w("## Result")
    w("")
    w(f"- Laws holding to 10^6: **{len(held)} / {SAMPLE_N}**")
    w(f"- Laws with a counterexample below 10^6: **{len(broke)} / {SAMPLE_N}**")
    w("")
    w("| DSL | modulus | residues | preperiod | result |")
    w("|---|---:|---|---:|---|")
    for r in results:
        law = r["law"]
        res = ", ".join(map(str, law["residues"]))
        if r["holds"]:
            verdict = "holds to 10^6"
        else:
            d = r["counterexample_detail"]
            verdict = (f"**first counterexample n = {d['n']}** "
                       f"(computed {d['computed']}, law predicts {d['law_predicts']})")
        w(f"| `{r['dsl']}` | {law['modulus']} | {res} | {law['from']} | {verdict} |")
    w("")
    w("## Per game")
    w("")
    for r in results:
        w(f"### `{r['dsl']}`")
        w("")
        w(f"- Rule: subtract s ∈ {r['pretty']}")
        w(f"- game_hash: `{r['game_hash']}`")
        w(f"- Tested to N = {r['N_harsh']:,} in {r['seconds']}s")
        w("")
        w("Census conjecture line, reproduced verbatim:")
        w("")
        w("```")
        w(r["conjecture_census"])
        w("```")
        w("")
        if r["holds"]:
            w("**holds to 10^6** — no counterexample found.")
        else:
            d = r["counterexample_detail"]
            w(f"**first counterexample: n = {d['n']}** — win/loss computation says "
              f"{d['computed']}, the law predicts {d['law_predicts']}.")
        w("")
    w("---")
    w("")
    w("All laws above are unproven conjectures pending human verification.")

    with open("HARSH_VERIFY.md", "w") as fh:
        fh.write("\n".join(L) + "\n")
    with open("harsh_verify_raw.json", "w") as fh:
        json.dump({
            "source": SRC, "seed": SEED, "sample_n": SAMPLE_N,
            "n_harsh": N_HARSH, "pool_size": len(pool),
            "held": len(held), "broke": len(broke),
            "total_seconds": round(time.time() - t0, 1),
            "results": results,
        }, fh, indent=1)

    print(f"\nholds to 10^6 : {len(held)}/{SAMPLE_N}")
    print(f"counterexample: {len(broke)}/{SAMPLE_N}")
    for r in broke:
        print(f"   {r['dsl']}  first n={r['first_counterexample']}")
    print(f"total time    : {time.time() - t0:.1f}s")
    print("wrote HARSH_VERIFY.md, harsh_verify_raw.json")


if __name__ == "__main__":
    main()
