#!/usr/bin/env python3
"""Wide-modulus rescan of the CHAOTIC games from the family census.

The census ran the standard detector stack, whose residue detector caps the
modulus at max_m=40. This script takes every game the census tiered CHAOTIC,
recomputes Grundy values at N=6000, and calls residue_characterization with
max_m=200.

Imports game_hunter read-only; modifies nothing in it. Writes CHAOTIC_RESCAN.md
and rescan_raw.json. No OEIS calls.

Firewall: this script reports laws and counts only. Conjecture wording comes
from gh.draft_conjectures -- this script never composes or rewords a conjecture
itself -- and it proposes no pattern relating any game's parameters to the
modulus that emerges.
"""

import json
import time

import game_hunter as gh

SRC = "family_census_raw.json"
N_RESCAN = 6000
MAX_M = 200


def conjecture_for(law, stats):
    """Verbatim conjecture line from the engine's own drafter."""
    det = {"arith": None, "period": None, "residue": law, "digitsum": None}
    for line in gh.draft_conjectures(det, stats):
        if line.startswith("CONJECTURE:"):
            return line
    return None


def main():
    t0 = time.time()
    src = json.load(open(SRC))
    chaotic = [r for r in src["records"] if r["tier"] == "CHAOTIC"]
    print(f"CHAOTIC games from census: {len(chaotic)}")

    records = []
    t_scan = time.time()
    for i, r in enumerate(chaotic, 1):
        rule = r["rule"]
        G = gh.grundy_sequence(rule, N_RESCAN)
        law = gh.residue_characterization(G, max_m=MAX_M)
        stats = gh.game_stats(rule, G)
        rec = {
            "rule": rule,
            "dsl": json.dumps(rule),
            "pretty": r["pretty"],
            "m": r["m"], "r": r["r"],
            "branch_order": r["branch_order"], "F_pretty": r["F_pretty"],
            "census_tier": r["tier"],
            "census_hash": r["game_hash"],
            "N_rescan": N_RESCAN,
            "max_m": MAX_M,
            "law": law,
            "conjecture": conjecture_for(law, stats) if law else None,
        }
        records.append(rec)
        if i % 200 == 0:
            print(f"  {i}/{len(chaotic)}  ({time.time() - t_scan:.0f}s)")

    scan_secs = time.time() - t_scan

    with_law = [x for x in records if x["law"]]
    no_law = [x for x in records if not x["law"]]
    beyond_40 = [x for x in with_law if x["law"]["modulus"] > 40]
    mod_counts = {}
    for x in with_law:
        k = x["law"]["modulus"]
        mod_counts[k] = mod_counts.get(k, 0) + 1

    records.sort(key=lambda x: (x["law"]["modulus"] if x["law"] else 10 ** 9,
                                x["m"], x["r"], x["branch_order"], x["F_pretty"]))

    L = []
    w = L.append
    w("# Wide-modulus rescan of the CHAOTIC games")
    w("")
    w("Generated by `rescan_chaotic.py`. Detector output at a finite range;")
    w("nothing here is proved.")
    w("")
    w("## What was rescanned")
    w("")
    w(f"- Source: `{SRC}`, every game the census tiered CHAOTIC "
      f"(**{len(chaotic)}** games)")
    w(f"- Grundy values recomputed at N = {N_RESCAN}")
    w(f"- `residue_characterization(G, max_m={MAX_M})`")
    w("- No OEIS calls.")
    w("")
    w(f"The census reached those CHAOTIC verdicts through `detect_all`, whose")
    w(f"residue detector caps the modulus at `max_m=40`. Raising the cap to")
    w(f"{MAX_M} is the only change; the range also moved from 3000 to {N_RESCAN}.")
    w("")
    w("Note on comparability: `detect_all` consults the residue detector only")
    w("when no periodicity is found, whereas this script calls the residue")
    w("detector directly. For these games that distinction is inert -- a CHAOTIC")
    w("verdict already means no periodicity was detected.")
    w("")
    w("## Reclassification count")
    w("")
    w(f"- CHAOTIC games rescanned: **{len(chaotic)}**")
    w(f"- Now showing a residue law at modulus ≤ {MAX_M}: **{len(with_law)}**")
    w(f"- Still \"none up to modulus {MAX_M}\": **{len(no_law)}**")
    w(f"- Of the laws found, modulus above the original cap of 40: **{len(beyond_40)}**")
    w("")
    if mod_counts:
        w("Modulus frequency among the newly detected laws:")
        w("")
        w("| modulus | games |")
        w("|---:|---:|")
        for k in sorted(mod_counts):
            w(f"| {k} | {mod_counts[k]} |")
        w("")
    w("## Rescan")
    w("")
    w("Sorted by modulus, then m. Games with no law sort last.")
    w("")
    w("| DSL | m | r | branch order | F | modulus | residues | preperiod |")
    w("|---|---:|---:|---|---|---:|---|---:|")
    for x in records:
        law = x["law"]
        if law:
            mod = str(law["modulus"])
            res = ", ".join(map(str, law["residues"]))
            pre = str(law["from"])
        else:
            mod = f"none up to modulus {MAX_M}"
            res = pre = "-"
        w(f"| `{x['dsl']}` | {x['m']} | {x['r']} | {x['branch_order']} | "
          f"`{x['F_pretty']}` | {mod} | {res} | {pre} |")
    w("")
    if with_law:
        w("## Conjecture lines for the newly detected laws")
        w("")
        w("Emitted by the engine's own drafter, reproduced verbatim.")
        w("")
        for x in records:
            if x["law"]:
                w(f"- `{x['dsl']}`")
                w("")
                w("  ```")
                w(f"  {x['conjecture']}")
                w("  ```")
                w("")
    w("---")
    w("")
    w("All laws above are unproven conjectures pending human verification.")

    with open("CHAOTIC_RESCAN.md", "w") as fh:
        fh.write("\n".join(L) + "\n")
    with open("rescan_raw.json", "w") as fh:
        json.dump({
            "source": SRC, "n_rescan": N_RESCAN, "max_m": MAX_M,
            "chaotic_games": len(chaotic),
            "with_law": len(with_law), "no_law": len(no_law),
            "modulus_above_40": len(beyond_40),
            "scan_seconds": round(scan_secs, 1),
            "records": records,
        }, fh, indent=1)

    print(f"\nrescanned        : {len(chaotic)}")
    print(f"law found        : {len(with_law)}")
    print(f"none up to {MAX_M}  : {len(no_law)}")
    print(f"modulus > 40     : {len(beyond_40)}")
    print(f"modulus freq     : {dict(sorted(mod_counts.items()))}")
    print(f"scan time        : {scan_secs:.1f}s   total {time.time() - t0:.1f}s")
    print("wrote CHAOTIC_RESCAN.md, rescan_raw.json")


if __name__ == "__main__":
    main()
