#!/usr/bin/env python3
"""Entry-13 workbook generator.

Emits ENTRY13_WORKBOOK.md for the shortlist rule
    ["ifmod", 5, 2, ["squares"], ["range", 1, 3]]

Imports game_hunter read-only; modifies nothing in it and writes nothing except
ENTRY13_WORKBOOK.md.

Workbook firewall: this script emits DATA ONLY -- the rule, the verbatim
conjecture line, a small-n table, and a cross-implementation check. It does not
emit residue arithmetic, closure/escape analysis, lemma suggestions, or any
account of why the law might hold. That analysis belongs to the human.
"""

import json
import subprocess
import sys
import time
from math import isqrt

import game_hunter as gh

RULE = ["ifmod", 5, 2, ["squares"], ["range", 1, 3]]
DEEP_N = 20000
CROSS_N = 1_000_000
OUT = "ENTRY13_WORKBOOK.md"


# ---------------------------------------------------------------------------
# (a) fresh analyze run -- verbatim conjecture line
# ---------------------------------------------------------------------------

def fresh_analyze(rule, N):
    """Run the analyze CLI as a subprocess and return (stdout, conjecture lines)."""
    dsl = json.dumps(rule)
    cmd = [sys.executable, "game_hunter.py", "analyze", "--rule", dsl, "--N", str(N)]
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        raise SystemExit(f"analyze failed (rc={p.returncode}):\n{p.stderr}")
    conj = [l.strip() for l in p.stdout.splitlines()
            if l.strip().startswith("CONJECTURE:")]
    return p.stdout, conj


# ---------------------------------------------------------------------------
# (c) fresh standalone move rule -- deliberately does NOT use gh.compile_rule
# ---------------------------------------------------------------------------

def moves_entry13(n):
    """Legal subtraction amounts at n, written from scratch for this one game.

    n = 2 (mod 5): the perfect squares k^2 with k^2 <= n.
    otherwise    : the amounts 1, 2, 3 that are <= n.
    """
    if n % 5 == 2:
        return [k * k for k in range(1, isqrt(n) + 1)]
    return [s for s in (1, 2, 3) if s <= n]


def standalone_p_flags(N):
    """isP[n] == 1 iff n is a P-position, by independent win/loss recursion."""
    isP = bytearray(N + 1)
    isP[0] = 1                      # no moves available: previous player wins
    for n in range(1, N + 1):
        found = 0
        if n % 5 == 2:
            k = 1
            while k * k <= n:
                if isP[n - k * k]:
                    found = 1
                    break
                k += 1
        else:
            for s in (1, 2, 3):
                if s <= n and isP[n - s]:
                    found = 1
                    break
        if not found:
            isP[n] = 1
    return isP


def first_counterexample(isP, modulus, residues, start):
    res = set(residues)
    for n in range(start, len(isP)):
        if bool(isP[n]) != (n % modulus in res):
            return n
    return None


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    t0 = time.time()

    # (a) verbatim conjecture from a fresh CLI run
    stdout, conj = fresh_analyze(RULE, DEEP_N)
    if not conj:
        raise SystemExit("no CONJECTURE line emitted at N=%d; stopping." % DEEP_N)

    # structured form of the same detection, for the cross-check comparison
    G_deep = gh.grundy_sequence(RULE, DEEP_N)
    det, _ = gh.detect_all(RULE, G_deep)
    law = det["residue"]
    if law is None:
        raise SystemExit("engine reported no residue law at N=%d; stopping." % DEEP_N)

    # (b) small-n table straight from the engine's own move set + Grundy values
    f_engine = gh.compile_rule(RULE)
    G_small = gh.grundy_sequence(RULE, 40)
    rows = []
    for n in range(0, 41):
        mv = sorted(f_engine(n))
        mv_s = "{" + ", ".join(map(str, mv)) + "}" if mv else "{} (none)"
        rows.append((n, n % 5, mv_s, "P" if G_small[n] == 0 else "N"))

    # (c) cross-implementation check
    t_cross = time.time()
    isP = standalone_p_flags(CROSS_N)
    cross_secs = time.time() - t_cross
    ce = first_counterexample(isP, law["modulus"], law["residues"], law["from"])

    # implementation agreement over the range both methods cover
    disagree = [n for n in range(DEEP_N + 1) if bool(isP[n]) != (G_deep[n] == 0)]

    L = []
    w = L.append
    w("# Entry 13 workbook")
    w("")
    w("Generated by `workbook.py`. Data only: rule, verbatim conjecture, small-n")
    w("table, cross-implementation check. No analysis of why the law might hold.")
    w("")

    w("## a. Rule and conjecture")
    w("")
    w(f"- **DSL**: `{json.dumps(RULE)}`")
    w(f"- **Human-readable**: subtract s ∈ {gh.pretty(RULE)}")
    w("")
    w(f"Fresh run: `python3 game_hunter.py analyze --rule '{json.dumps(RULE)}' --N {DEEP_N}`")
    w("")
    w("Conjecture line, copied verbatim from that run's output:")
    w("")
    w("```")
    for c in conj:
        w(c)
    w("```")
    w("")

    w("## b. Positions n = 0..40")
    w("")
    w("Move sets and P/N values are the engine's own, at N=40.")
    w("")
    w("| n | n mod 5 | legal move set | P or N |")
    w("|---:|---:|---|:---:|")
    for n, r, mv, pn in rows:
        w(f"| {n} | {r} | `{mv}` | {pn} |")
    w("")

    w("## c. Cross-implementation check")
    w("")
    w("`moves_entry13` / `standalone_p_flags` in `workbook.py` re-implement this")
    w("game's move rule and win/loss recursion from scratch. They do not call")
    w("`compile_rule`, `grundy_sequence`, or any detector.")
    w("")
    w(f"- Range recomputed: n = 0 .. {CROSS_N:,} ({cross_secs:.1f}s)")
    w(f"- Law tested: P-positions exactly n ≡ "
      f"{', '.join(map(str, law['residues']))} (mod {law['modulus']}), "
      f"for n ≥ {law['from']}")
    w("")
    if ce is None:
        w("**law holds to 10^6, no counterexamples**")
    else:
        w(f"**first counterexample: n = {ce}** "
          f"(standalone says {'P' if isP[ce] else 'N'}; "
          f"law predicts {'P' if ce % law['modulus'] in set(law['residues']) else 'N'})")
    w("")
    w("Implementation agreement, over the range both methods cover "
      f"(n = 0 .. {DEEP_N:,}):")
    w("")
    if disagree:
        w(f"- **{len(disagree)} disagreement(s)**; first at n = {disagree[0]}")
    else:
        w(f"- standalone P/N matches `grundy_sequence(...) == 0` at every n; "
          f"0 disagreements")
    w("")
    w("---")
    w("")
    w("This workbook records data only. The conjecture above is unproven.")

    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")

    print(f"wrote {OUT}")
    print(f"  conjecture   : {conj[0]}")
    print(f"  law          : mod {law['modulus']} residues {law['residues']} from {law['from']}")
    print(f"  counterexample to 10^6: {ce if ce is not None else 'none'}")
    print(f"  impl disagreements 0..{DEEP_N}: {len(disagree)}")
    print(f"  total {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
